### ISSUE TITLE
Add Infrastructure to the menu

### ISSUE THREAD

**Issue by mgialong215** [notional-labs/notional.ventures#21]
Add Infrastructure after Staking section: 
* [x] Snapshots from https://snapshot.notional.ventures/
* [x] Relaying stats

**Comment by lichdu29** [comment]
Finish infra section and modal design snapshot 
![Screen Shot 2022-07-07 at 15 53 45](https://user-images.githubusercontent.com/61083705/177733508-0a
![Screen Shot 2022-07-07 at 15 54 48](https://user-images.githubusercontent.com/61083705/177733724-a6793747-3dba-40df-9f98-455756a2b494.png)
a947aa-b525-4a86-a39c-2d5157c8443d.png)
n

**Comment by lichdu29** [comment]
Finish infra section and modal design snapshot
![Screen Shot 2022-07-07 at 15 54 29](https://user-images.githubusercontent.com/61083705/177734008-cf8edc92-98a3-439b-b6d5-f2ab5f6afa0d.png)
![Screen Shot 2022-07-02 at 01 19 24](https://user-images.githubusercontent.com/61083705/177734021-cb25f241-b837-43de-9df9-9ae6473fccc9.png)

**Comment by lichdu29** [comment]
Finish infra section and modal design snapshot
![Screen Shot 2022-07-07 at 15 54 29](https://user-images.githubusercontent.com/61083705/177734242-0f8021e5-e8ae-4c1e-954f-0389ca0f3c88.png)

![Screen Shot 2022-07-07 at 15 56 59](https://user-images.githubusercontent.com/61083705/177734225-74f08ead-ef2e-4934-bb11-b323bf10879e.png)

**Comment by lichdu29** [comment]
adding layout for snapshot
![Screen Shot 2022-07-09 at 19 17 59](https://user-images.githubusercontent.com/61083705/178105443-136658b6-6cad-4c40-b432-fb4d27124dde.png)

**Comment by lichdu29** [comment]
working on modal and api

**Comment by lichdu29** [comment]
done snapshot and represent relayer
