### ISSUE TITLE
Update new validator to staking site

### ISSUE THREAD

**Issue by mgialong215** [notional-labs/notional.ventures#22]
Create custom api and update Fetch.AI validator on Staking site
https://www.mintscan.io/fetchai/validators/fetchvaloper1s9myentgxavnpw7648an2v6zvvpza0axa6dd0x

**Comment by lichdu29** [comment]
> Create custom api and update Fetch.AI validator on Staking site https://www.mintscan.io/fetchai/validators/fetchvaloper1s9myentgxavnpw7648an2v6zvvpza0axa6dd0x

Add front-end for fetch.ai, working on custom API for this chain (will be updated later) 
![Screen Shot 2022-07-02 at 01 19 24](https://user-images.githubusercontent.com/61083705/176949575-ebf03596-570f-4af0-8f5f-6a08b1131fd8.png)

**Comment by lichdu29** [comment]
done

**Comment by MasterPi-2124** [comment]
not done

**Comment by MasterPi-2124** [comment]
now done

**Comment by mgialong215** [comment]
https://www.mintscan.io/umee/validators/umeevaloper1dmahqt84r9je3sqvljzjrttjj78cmrf39k5zhs
need to add Umee

**Comment by lichdu29** [comment]
![Screen Shot 2022-08-17 at 16 49 34](https://user-images.githubusercontent.com/61083705/185089416-2b355c49-3b8f-4d15-a912-ed1f2edc6f4b.png)
done
