### ISSUE TITLE
Add Injective, Passage

### ISSUE THREAD

**Issue by mgialong215** [notional-labs/notional.ventures#28]
https://www.mintscan.io/injective/validators/injvaloper16eg6wf2k6v0lzwu2vsrhxhe0tcycgr7jm98nyz
https://www.mintscan.io/passage/validators/pasgvaloper14npnd73z5qjwz4az2dpw6vcdvkj29qg0cgar4j

**Comment by mgialong215** [comment]
CC8D91AE72CD6156C5064524B4BDADC97405DCC7 INJ


AF129E73E9CC68AD9A18F42973C5CA6CB6CC8F7B PASG

**Comment by lichdu29** [comment]
got it working on UI @MasterPi-2124 working on API

**Comment by MasterPi-2124** [comment]
thanks @lichdu29

**Comment by lichdu29** [comment]
added injective

**Comment by MasterPi-2124** [comment]
added passage
